export default function Head() {
  return (
    <>
      <title>iwanttotrackyou.com</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <meta
        property="og:image"
        content="https://media.codingcat.dev/image/upload/f_jpg/main-codingcatdev-photo/iwanttotrackyou.png"
      />
      <meta name="description" content="A funny Bytes.dev prank" />
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:site" content="@CodingCatDev" />
      <meta name="twitter:creator" content="@CodingCatDev" />
      <meta property="fb:app_id" content="336062137813036" />
      <meta property="og:description" content="A funny Bytes.dev prank" />
      <meta property="og:type" content="website" />
      <meta
        property="og:image"
        content="https://media.codingcat.dev/image/upload/f_jpg/dev-codingcatdev-photo/v60h88eohd7ufghkspgo"
      />
      <meta
        property="og:image:alt"
        content="Bytes.dev article number #156 Answer"
      />
    </>
  );
}
